package siki;

import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static siki.connection.buatkoneks;

/**
 *
 * @author briandparmana 2201010659
 * TGL: 2024-06-15
 */
public class jFormObat extends javax.swing.JFrame {
    DefaultTableModel TM = new DefaultTableModel();
    /**
     * Creates new form jFormObat
     */
    public jFormObat() throws SQLException{
        initComponents();
        jTable1.setModel(TM);
        TM.addColumn("ID_Pengunjung");
        TM.addColumn("Tanggal");
        TM.addColumn("Nama_Pengunjung");
        TM.addColumn("Keluhan");
        TM.addColumn("Nama_Obat");
        TM.addColumn("Jumlah_Obat");
        
        this.setTitle("Sistem Informasi Kesehatan INSTIKI (SIKI)");
        ImageIcon IC = new ImageIcon("src/img/instiki.png");
        this.setIconImage(IC.getImage());
        
        List_All();
        kosongkanform();
        loadphoto("");
    }
    
    private void loadphoto(String idx){
        String nopic = "img/nopic.png";
        String ph = "img/"+idx+".png";
        BufferedImage photoip = loadIMG.loadImage(ph);
        if(photoip == null){
            photoip = loadIMG.loadImage(nopic);
        }
        ImageIcon iconphoto = new ImageIcon(photoip);
        photo.setIcon(iconphoto);
    }
    
    private void List_All() throws SQLException{
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        Connection cnn = buatkoneks();
        if(!cnn.isClosed() ){
            
            String sql = "SELECT * FROM buku_tamu;";
            PreparedStatement PS = cnn.prepareStatement(sql);
            ResultSet rs = PS.executeQuery();
            while(rs.next()){
                Object[] dta = new Object[6];
                dta[0] = rs.getInt("ID_Pengunjung");
                dta[1] = rs.getString("Tanggal");
                dta[2] = rs.getString("Nama_Pengunjung");
                dta[3] = rs.getString("Keluhan");
                dta[4] = rs.getString("Nama_Obat");
                dta[5] = rs.getInt("Jumlah_Obat");
                TM.addRow(dta);
            
            }
        }
    }
    
    private void StoreData() throws SQLException{
        Connection cnn = buatkoneks();
        String TG = txTGL.getText();
        String NP = txNP.getText();
        String KL = txKLHN.getText();
        String NB = txNOBT.getText();
        int JM = Integer.parseInt(txJMLH.getText());
         if(!cnn.isClosed() ){
             PreparedStatement PS = cnn.prepareStatement("INSERT INTO buku_tamu(Tanggal, Nama_Pengunjung, Keluhan, Nama_Obat, Jumlah_Obat) VALUES(?,?,?,?,?);");
             PS.setString(1, TG);
             PS.setString(2, NP);
             PS.setString(3, KL);
             PS.setString(4, NB);
             PS.setInt(5, JM);
             PS.executeUpdate();
         }
    }
    
    private void UpdateData() throws SQLException{
        Connection cnn = buatkoneks();
        if(!cnn.isClosed() ){
            PreparedStatement PS = cnn.prepareStatement("UPDATE buku_tamu SET Tanggal=?, Nama_Pengunjung=?, Keluhan=?, Nama_Obat=?, Jumlah_Obat=? WHERE ID_Pengunjung=?;");
            PS.setString(1, txTGL.getText());
            PS.setString(2, txNP.getText());
            PS.setString(3, txKLHN.getText());
            PS.setString(4, txNOBT.getText());
            PS.setInt(5, Integer.parseInt(txJMLH.getText()));
            PS.setInt(6, Integer.parseInt(txID.getText()));
            PS.executeUpdate();
            cnn.close();
        }
    }
    
    private void DestroyData() throws SQLException{
        Connection cnn = buatkoneks();
        if(!cnn.isClosed() ){
            PreparedStatement PS = cnn.prepareStatement("DELETE FROM buku_tamu WHERE ID_Pengunjung=?;");
            PS.setString(1, txID.getText());
            PS.executeUpdate();
            cnn.close();   
        }
    }
    
    private void kosongkanform(){
        txID.setText("");
        txTGL.setText("");
        txNP.setText("");
        txKLHN.setText("");
        txNOBT.setText("");
        txJMLH.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txTGL = new javax.swing.JTextField();
        txNP = new javax.swing.JTextField();
        txKLHN = new javax.swing.JTextField();
        txNOBT = new javax.swing.JTextField();
        txJMLH = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnINPUT = new javax.swing.JButton();
        btnCLOSE = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setText("Sistem Informasi Kesehatan INSTIKI (SIKI)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Pengunjung", "Tanggal", "Nama_Pengunjung", "Keluhan", "Nama_Obat", "Jumlah_Obat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setText("Buku Tamu POLIKLINIK INSTIKI");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel3.setText("ID_Pengunjung");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel4.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel5.setText("Nama Pengunjung");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel6.setText("Keluhan");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel7.setText("Nama Obat");

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel8.setText("Jumlah Obat");

        txID.setText("jTextField1");
        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txTGL.setText("jTextField2");
        txTGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTGLActionPerformed(evt);
            }
        });

        txNP.setText("jTextField3");
        txNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNPActionPerformed(evt);
            }
        });

        txKLHN.setText("jTextField4");
        txKLHN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKLHNActionPerformed(evt);
            }
        });

        txNOBT.setText("jTextField5");
        txNOBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNOBTActionPerformed(evt);
            }
        });

        txJMLH.setText("jTextField6");
        txJMLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJMLHActionPerformed(evt);
            }
        });

        btnINPUT.setText("INPUT");
        btnINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINPUTActionPerformed(evt);
            }
        });

        btnCLOSE.setText("CLOSE");
        btnCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLOSEActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnDELETE.setText("DELETE");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        photo.setBackground(new java.awt.Color(255, 255, 255));
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txNOBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                                    .addComponent(txKLHN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txJMLH)
                                    .addComponent(txTGL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(55, 55, 55)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txKLHN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txNOBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txJMLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txTGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTGLActionPerformed

    private void txNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNPActionPerformed

    private void txKLHNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKLHNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKLHNActionPerformed

    private void txNOBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNOBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNOBTActionPerformed

    private void txJMLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJMLHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJMLHActionPerformed

    private void btnINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINPUTActionPerformed
        if( btnINPUT.getText().equals("INPUT")){
            btnINPUT.setText("SUBMIT");
            btnCLOSE.setText("CANCEL");
            kosongkanform();
            jTable1.setEnabled(false);
        }else{
            btnINPUT.setText("INPUT");
            btnCLOSE.setText("CLOSE");
            jTable1.setEnabled(true);
            try {
                StoreData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(jFormObat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnINPUTActionPerformed

    private void btnCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLOSEActionPerformed
        if(btnCLOSE.getText().equals("CLOSE")){
           dispose(); 
        }else{
            btnCLOSE.setText("CLOSE");
            btnINPUT.setText("INPUT");
        }
    }//GEN-LAST:event_btnCLOSEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txID.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        txTGL.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        txNP.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
        txKLHN.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
        txNOBT.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
        txJMLH.setText(jTable1.getValueAt(jTable1.getSelectedRow(),5).toString());
        loadphoto(txID.getText());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        try {
            UpdateData();
            List_All();
            JOptionPane.showMessageDialog(this, "Data Telah Diupdate");
        } catch (SQLException ex) {
            Logger.getLogger(jFormObat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        int jwb = JOptionPane.showOptionDialog(this, "Yakin Akan Menghapus Data "+txNP.getText()+"?", "Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        if(jwb == JOptionPane.YES_OPTION){
            try {
                DestroyData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(jFormObat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jFormObat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jFormObat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLOSE;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnINPUT;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txJMLH;
    private javax.swing.JTextField txKLHN;
    private javax.swing.JTextField txNOBT;
    private javax.swing.JTextField txNP;
    private javax.swing.JTextField txTGL;
    // End of variables declaration//GEN-END:variables
}
